### ISSUE TITLE
These might be in the wrong place

### ISSUE THREAD

**Issue by daryl-cecile** [projectfunction/pf-task-dress-the-site-TurtleRosie#3]
https://github.com/projectfunction/pf-task-dress-the-site-TurtleRosie/blob/0a86a678ed55fa6a22b29528b77fcefc249da49f/style.css#L4-L5

This should probably be in the `#navbar ul` css ruleset as its the UL element that needs to change flex direction

**Comment by TurtleRosie** [comment]
I had no idea you could combine things like that (ie #navbar plus ul) - very helpful!
